# syntax=docker/dockerfile:1.7
FROM node:20-alpine AS base
WORKDIR /workspace
ENV PNPM_HOME=/root/.local/share/pnpm
RUN corepack enable

FROM base AS install
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY api/package.json api/package.json
COPY web/package.json web/package.json
COPY pay/package.json pay/package.json
RUN pnpm install --filter web... --frozen-lockfile

FROM install AS build
COPY . .
RUN pnpm --filter web... build

FROM nginx:1.27-alpine AS runtime
COPY nginx/default.web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/web/dist /usr/share/nginx/html
COPY docker/web-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD [ "nginx", "-g", "daemon off;" ]
