{
 "title": "Flash Ticket - Business",
 "description": "A business metrics for Flash Ticket service.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Queue Status - Real-time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(queue_waiting_users_total)", "legendFormat": "Waiting" },
    { "expr": "sum(queue_ready_users_total)", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Order Status",
   "type": "timeseries",
   "description": "Time series for order status",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "sum(orders_created_total)", "legendFormat": "Created Orders" },
    { "expr": "sum(orders_hold_total)", "legendFormat": "On Hold" },
    { "expr": "sum(orders_paid_total)", "legendFormat": "Paid Orders" },
    { "expr": "sum(orders_cancelled_total)", "legendFormat": "Cancelled" }
   ]
  },
  {
   "title": "Payment Status - Real-time",
   "type": "timeseries",
   "description": "Payment panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sum(payments_pending_total)", "legendFormat": "Pending" },
    { "expr": "sum(payments_successful_total)", "legendFormat": "Successful pay" },
    { "expr": "sum(payments_failed_total)", "legendFormat": "Failed pay" }
   ]
  },
  {
   "title": "Queue Conversion Rate",
   "type": "timeseries",
   "description": "Percentage of Real user",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(sum(queue_ready_users_total) / (sum(queue_waiting_users_total) + sum(queue_ready_users_total))) * 100",
     "legendFormat": "Active user percentage"
    }
   ]
  },
  {
   "title": "Order Success Rate",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(orders_paid_total) / sum(orders_created_total)) * 100",
     "legendFormat": "Order Success Rate"
    }
   ]
  },
  {
   "title": "Payment Success Rate",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(payments_successful_total) / (sum(payments_successful_total) + sum(payments_failed_total) + sum(payments_pending_total)) * 100",
     "legendFormat": "Payment Success Rate"
    }
   ]
  },
  {
   "title": "Failed History",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expr": "rate(orders_failed_total[5m])", "legendFormat": "Failed Orders" },
    {
     "expr": "rate(payments_failed_total[5m])\r\n",
     "legendFormat": "Failed Payments"
    }
   ]
  },
  {
   "title": "Order Failed Count",
   "type": "timeseries",
   "description": "Order Failed Count thru 5mins",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(orders_failed_total[5m])", "legendFormat": "Orders Created (per second)" }
   ]
  },
  {
   "title": "Payment Failed Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(payments_failed_total[5m])",
     "legendFormat": "Payment Success Rate (%)"
    }
   ]
  }
 ]
}