apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flash-tickets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CloudDx/flash-ticket-final.git
    targetRevision: main
    path: gitops/argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
