apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flash-tickets-pay
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CloudDx/flash-ticket-final.git
    targetRevision: main
    path: gitops/apps/pay/base
  destination:
    server: https://kubernetes.default.svc
    namespace: flash-ticket
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
