apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flash-gateway-hpa
  namespace: flash-ticket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flash-gateway
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 3
        periodSeconds: 30
      selectPolicy: Max