apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flash-pay-hpa
  namespace: flash-ticket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flash-pay
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Pay worker는 더 안정적으로 스케일다운
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max